const items = [
  {
    name: "Express",
    price: 3,
    category: "Cafés",
    image:
      "https://thumbs.dreamstime.com/z/caf%C3%A9-de-caf%C3%A9-express-15779784.jpg",
  },
  {
    name: "Capucin",
    price: 4,
    category: "Cafés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ94v6gBk341K9WcKr9iksiBkP79XhaFeOerA&usqp=CAU",
  },
  {
    name: "American",
    price: 3,
    category: "Cafés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGLyTofk0taq3lRxO_EBDSk4AN7W7cdG24eQ&usqp=CAU",
  },
  {
    name: "Café creme",
    price: 4,
    category: "Cafés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-_Tnnv1uvyXw3yR-wc6rrssP4EDNY8vgB7Q&usqp=CAU",
  },
  {
    name: "Cappuccino",
    price: 5,
    category: "Cafés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqh1tWEZPl3Vw8gRvgxgOju-yjYO2u0yoUiA&usqp=CAU",
  },
  {
    name: "Café Turc",
    price: 5,
    category: "Cafés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRHjxpeHgIWZJLrYObHXL8SH5_whp647DUuVA&usqp=CAU",
  },
  {
    name: "Thé a la menthe",
    price: 3,
    category: "Thés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcStjcuU5uG9WOVN64dNjDz6uoSWQjneqW53yA&usqp=CAU",
  },
  {
    name: "Thé infusion",
    price: 3,
    category: "Thés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQculGEcRtxY1EsABE3lcyFAzlA6LmIWE_lrQ&usqp=CAU",
  },
  {
    name: "Thé aux amandes",
    price: 5,
    category: "Thés",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQNhsXFY4cQDzPyPIhc-yrmJJa29lGVfE9hRg&usqp=CAU",
  },
  {
    name: "Eau Minérale 0.5L",
    price: 1,
    category: "Boissons Fraiches",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbzKc8TX0xmB8n7sQZ4mtsIX8WVn7mwn-DOA&usqp=CAU",
  },
  {
    name: "Eau Minérale 1.5L",
    price: 2,
    category: "Boissons Fraiches",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMhp25DR9UJK53s3soFcO1Z7BY7QIUjeLsJw&usqp=CAU",
  },
  {
    name: "Soda",
    price: 4,
    category: "Boissons Fraiches",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCXzh-9PDG_qOouItNMgQxRsHlsmT65W66yQ&usqp=CAU",
  },
  {
    name: "Energy drink",
    price: 7,
    category: "Boissons Fraiches",
    image: "https://m.media-amazon.com/images/I/71NYYjONBzL._SX522_PIbundle-4,TopRight,0,0_AA522SH20_.jpg",
  },
  {
    name: "Chocolat chaud",
    price: 5,
    category: "Boissons Chaudes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMpH5nO46uWkk2GmODivibvxaDvAjiRYTPzA&usqp=CAU",
  },
  {
    name: "Chocolat chaud Kinder",
    price: 6,
    category: "Boissons Chaudes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQHSxAUG3OrPoAq0TgoOcYgJrHuMZK-97KmZw&usqp=CAU",
  },
  {
    name: "Chocolat chaud Oreo",
    price: 6,
    category: "Boissons Chaudes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6a1EltAGuZX6N5nghFhDE44f5ctCg5ahW5Q&usqp=CAU",
  },
  {
    name: "Vanille",
    price: 7,
    category: "Milkshakes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDUWexVJh9EGbLzSpE7VskNawohotTfO5Zng&usqp=CAU",
  },
  {
    name: "Chocolat",
    price: 8,
    category: "Milkshakes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQM4KlnUMD2RAQkN2lHyCJW-u6tJSVU6wpf7w&usqp=CAU",
  },
  {
    name: "Fraise",
    price: 8,
    category: "Milkshakes",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm_4baMzFiKH7WXww0yZWbKlwqMMKHXYPCJQ&usqp=CAU",
  },
  {
    name: "Citronnade",
    price: 6,
    category: " Jus",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgqPMsbL6dn_VXHK8II8pNHVZgJIQSiXm0ag&usqp=CAU",
  },
  {
    name: "Orange",
    price: 6,
    category: " Jus",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu0WLo_iY0Oh9g7STS8SJfilOuJvSgc1tDag&usqp=CAU",
  },
  {
    name: "Banane",
    price: 7,
    category: " Jus",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSk06UD6ioFLgiV6_o6MD7pg7jOkCca05xREA&usqp=CAU",
  },
  {
    name: "Fraise",
    price: 7,
    category: " Jus",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtjmbAKJiSNkhew4poWUK6ORSvzI-qWIKbdw&usqp=CAU",
  },
  {
    name: "Fraise Banane",
    price: 9,
    category: "Smoothies",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQrLZ3YBqeRwVmQWIiMeBtBo-2-zIy1EHWWpw&usqp=CAU",
  },
  {
    name: "Ananas Mangue",
    price: 10,
    category: "Smoothies",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHQzSUiR0GkuYuVDl3SbI17-VhGxeSfXMIOA&usqp=CAU",
  },
  {
    name: "Framboise",
    price: 10,
    category: "Smoothies",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSBVvv1Wl_pZWsXOn7-UHKKCjw6aqoJ1R1TuA&usqp=CAU",
  },
  {
    name: "Virgin",
    price: 8,
    category: "Mojitos",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQmlj8gp2u1JoEVEqEW4y4KWmi0eE10XtxcQ&usqp=CAU",
  },
  {
    name: "Red Mojito",
    price: 10,
    category: "Mojitos",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSw8XMtEbolq6vltzmy-Eh-S4ERkwX6J7j-eA&usqp=CAU",
  },
  {
    name: "Blue Mojito",
    price: 10,
    category: "Mojitos",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4cr40IbTF6PoQWgn9wcYYTqFrQ9NayuXaqg&usqp=CAU",
  },
  {
    name: "Chocolat",
    price: 7,
    category: "Crepes Sucrées",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxBxnhjtRXsHxfUHzIWZmrc1rcIIzh7xtB7Q&usqp=CAU",
  },
  {
    name: "Chocolat , Banane",
    price: 8,
    category: "Crepes Sucrées",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkV7pRfSbpbSI7xQtt6jLmCbrccY0-JcPyug&usqp=CAU",
  },
  {
    name: "Chocolat ",
    price: 7,
    category: "Gaufres Sucrées",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYMfs9hxVozNXUjQHW-FPNr9cjpwg2il0S3Q&usqp=CAU",
  },
  {
    name: "Chocolat , Banane",
    price: 8,
    category: "Gaufres Sucrées",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyXxi-rUhVFdur4OWRlcNs__7R5qzDd2jV9A&usqp=CAU",
  },
  {
    name: "Jambon , Fromage",
    price: 7,
    category: "Crepes Salées",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPgqE6W2EqPlpo0_TYRgjX_4QwezsF2TcVeA&usqp=CAU",
  },
  {
    name: "Thon , Formage",
    price: 8,
    category: "Crepes Salées",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTi7tPgZSQpUe3DrlEIsR-fsqY0BNoFRlcbYw&usqp=CAU",
  },
  {
    name: "Thon",
    price: 5,
    category: "Tabouna",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsGAFzNtliptSeohr-dwMpFTsEF3x4jSf86Q&usqp=CAU",
  },
  {
    name: "Escalope",
    price: 6,
    category: "Tabouna",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsGAFzNtliptSeohr-dwMpFTsEF3x4jSf86Q&usqp=CAU",
  },
  {
    name: "Corden Bleu",
    price: 7,
    category: "Tabouna",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsGAFzNtliptSeohr-dwMpFTsEF3x4jSf86Q&usqp=CAU",
  },
  {
    name: "Thon",
    price: 6,
    category: "Makloub",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDamI11ErKi0msbfaCdTbpIDiQOKgjif2IuQ&usqp=CAU",
  },
  {
    name: "Escalope",
    price: 7,
    category: "Makloub",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDamI11ErKi0msbfaCdTbpIDiQOKgjif2IuQ&usqp=CAU",
  },
  {
    name: "Corden Bleu",
    price: 8,
    category: "Makloub",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDamI11ErKi0msbfaCdTbpIDiQOKgjif2IuQ&usqp=CAU",
  },
  {
    name: "Escalope",
    price: 7,
    category: "Baguette Farcie",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVLs3rdEEzq75T_UhTLbw_8myeDwLWnKfWQw&usqp=CAU",
  },
  {
    name: "Corden Bleu",
    price: 8,
    category: "Baguette Farcie",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQVLs3rdEEzq75T_UhTLbw_8myeDwLWnKfWQw&usqp=CAU",
  },
  {
    name: "Margherita",
    price: 10,
    category: "Pizza",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSa2qRMTC5NvqcQavJjyK2FqgevKQcGKGV8RQ&usqp=CAU",
  },
  {
    name: "Neptune",
    price: 12,
    category: "Pizza",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRAUnBYYFc7_CUlCXpjl08wiITquBKJdy8X6A&usqp=CAU",
  },
  {
    name: "4 saisons",
    price: 14,
    category: "Pizza",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUTmEaBaXeP-sKYGRH95ELxg3Av_4ueLo3jA&usqp=CAU",
  },
  {
    name: "4 fromages",
    price: 17,
    category: "Pizza",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSeSrmrQ40G-Jy61pqaYW3Pfd87EWREMnu9ag&usqp=CAU",
  },
];


module.exports = items;